wandb_version: 1

Architecture:
  desc: null
  value: u2net_lite
trainer:
  desc: null
  value: Trainer
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681737387.150499
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.16
      5: 0.14.2
      8:
      - 4
      - 5
