name: U2NetLite_scratch_1gpu-bs4_KNC_size320x320
n_gpu: 1
arch:
    type: u2net_lite
    args: {}
data_loader:
    type: KNC_DataLoader
    args:
        batch_size: 4
        shuffle: true
        num_workers: 1
        validation_split: 0.1
        output_size: 320
        crop_size: 288
optimizer:
    type: Adam
    args:
        lr: 0.001
        weight_decay: 0
        eps: 1.0e-08
        betas:
        - 0.9
        - 0.999
loss: multi_bce_fusion
metrics:
- mae
- sm
lr_scheduler:
    type: StepLR
    args:
        step_size: 50
        gamma: 0.1
trainer:
    type: Trainer
    epochs: 1000
    save_dir: saved/
    save_period: 10
    verbosity: 1
    visual_tool: wandb
    project: cvps23
    name: U2NetLite_scratch_1gpu-bs4_KNC_size320x320
    api_key_file: ./configs/api-key/tuanlda78202
    entity: tuanlda78202
test:
    save_dir: saved/tested
    n_sample: 1000
    batch_size: 32
